version: '3'

services:
  postgres-compose:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/var/lib/postgresql/data 
    networks:
      - postgres-compose-network

networks: 
  postgres-compose-network:
    driver: bridge